//______________________________________________________PACKAGE___________________________________________________________

/**
 *This package contains all the classes required to execute the CYK algorithm 
 */

package model;

//______________________________________________________IMPORTS___________________________________________________________

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

//______________________________________________________THE CLASS__________________________________________________________

/**
* This class defines the basic attributes and methods to execute the CYK algorithm 
* @author Luis Felipe Sanchez Vega
*/

public class CYK_algorithm{

//______________________________________________________ATTRIBUTES___________________________________________________________

    private String w;
    private Grammar grammar;
    private HashSet<String>[][] matrix;

//______________________________________________________METHODS___________________________________________________________
    
    
    /**
     * The constructor of an instance of the CYK algorithm<br><br>
     */
    public CYK_algorithm() {
    	
    	this.grammar = null;
    	this.w = null;
    	
    }
    
    
    /**
     * This method calls all the necessary method to perform the CYK
     * <b>pre: </b> The CYK instance must not be null <br><br>
     * <b>pos: </b> The matrix has modified its content <br><br>
     * @return A boolean that tells if a given string is generated by the grammar <br><br>
     */
    @SuppressWarnings("unchecked")
	public boolean cyk(){

        boolean generateString = false;
       
        matrix = new HashSet[w.length()+1][w.length()+1];
        
        initialize();
        fillMatrix();

        if (matrix[1][matrix.length-1].contains(grammar.getInitialVariable())) {
            generateString = true;
            
        }
    
        return generateString;

    }
    
    /**
	 * This method returns a matrix of sets.  <br><br> 
	 * <b>Pre: </b> The CYK must not be null <br><br>
	 * @return A matrix which contains sets of variables <br><br>
	 */
    public HashSet<String>[][] getHS(){

        return matrix;

    }
    
    /**
	 * This method returns the evaluated string w.  <br><br> 
	 * <b>Pre: </b> The CYK must not be null <br><br>
	 * @return A string w that is going to be used in the algorithm <br><br>
	 */
    public String getCad(){
        return w;
    }
    
    /**
   	 * This method modifies the grammar used by CYK <br><br>
   	 * <b>Pre: </b> The CYK must not be null <br><br>
   	 * <b>Post: </b> The CYK has a different grammar <br><br>
   	 * @param grammar the new grammar <br><br>
   	 */
    public void setGrammar(Grammar grammar) {
    	this.grammar = grammar;
    }
    
    /**
	 * This method returns the evaluated grammar.  <br><br> 
	 * <b>Pre: </b> The CYK must not be null <br><br>
	 * @return A grammar G that is going to be used in the algorithm <br><br>
	 */
    public Grammar getGrammar() {
    	return grammar;
    }   
    
    /**
   	 * This method modifies the string used by CYK <br><br>
   	 * <b>Pre: </b> The CYK must not be null <br><br>
   	 * <b>Post: </b> The CYK has a different string <br><br>
   	 * @param w the new string <br><br>
   	 */
    public void setCad(String w) {
    	this.w = w;
    }
    
    /**
   	 * This method fills the matrix with sets that contains variables, in order to tell if the initial variable belongs to certain position if the matrix <br><br>
   	 * <b>Pre: </b> The CYK must not be null <br><br>
   	 * <b>Post: </b> The matrix has modified some of its values <br><br>
   	 */
    private void fillMatrix(){
        
        for (int j = 2; j < matrix.length; j++) {
            
            for (int i = 1; i < (matrix.length-j)+1; i++) {
                
                matrix[i][j] = new HashSet<>();
                
                for (int k = 1; k <= j-1; k++) {
                    
                    HashSet<String> set1 = new HashSet<String>();
                    HashSet<String> set2 = new HashSet<String>();

                    if (matrix[i][k] != null) {
                        set1.addAll(matrix[i][k]);
                    }

                    if (matrix[i+k][j-k] != null) {
                        set2.addAll(matrix[i+k][j-k]);
                    }
                    
                    List<String> list = new ArrayList<>(concatenateSet(set1, set2));
                    
                    HashSet<String> setToAdd = grammar.isProduceFor(list);
                    
                    if (setToAdd != null) {
                        matrix[i][j].addAll(setToAdd);
                    }  

                }
               
            }
            
        }

    }
    
    /**
   	 * This method fills the first column of the matrix with the variables that produce each char of the given string <br><br>
   	 * <b>Pre: </b> The CYK must not be null <br><br>
   	 * <b>Post: </b> The matrix has modified the content of its firs column <br><br>
   	 */
    private void initialize(){
        
        String c;
        
        for (int i = 0; i < w.length(); i++) {
            
            c = String.valueOf(w.charAt(i));
            List<String> list = new ArrayList<>();
            list.add(c);

            matrix[i+1][1] = grammar.isProduceFor(list);

        }

    }
    
    /**
   	 * This method concatenates the elements of two given sets <br><br>
   	 * <b>Pre: </b> The CYK must not be null <br><br>
   	 * @param s1 The first set <br><br>
   	 * @param s2 The second set
   	 * @return A set with the elements of the given sets concatenated.
   	 */
    private HashSet<String> concatenateSet(HashSet<String> s1, HashSet<String> s2){

        HashSet<String> set = new HashSet<>();

        if (!(s1.size() == 0 || s2.size() == 0)) {
            
            for (String string : s1) {
                
                for (String string2 : s2) {
                    
                    set.add(string+string2);

                }
            }
        }

        return set;

    }

}